// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi0ggU_RTqCbTKO1pGL0kdkVmn1OYC85A',
    appId: '1:614795866086:web:eb40a28515a49dbb663027',
    messagingSenderId: '614795866086',
    projectId: 'kigali-directory-4d052',
    authDomain: 'kigali-directory-4d052.firebaseapp.com',
    storageBucket: 'kigali-directory-4d052.firebasestorage.app',
    measurementId: 'G-1V5FR84EST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPwlv_hAB2yyesj6X5WmHFWDzuF7Ieqs',
    appId: '1:614795866086:android:f436d778b5d46223663027',
    messagingSenderId: '614795866086',
    projectId: 'kigali-directory-4d052',
    storageBucket: 'kigali-directory-4d052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6g9WoLpwd2A11KHfg60X7sUogd0C0xAk',
    appId: '1:614795866086:ios:d9656a01fed195ab663027',
    messagingSenderId: '614795866086',
    projectId: 'kigali-directory-4d052',
    storageBucket: 'kigali-directory-4d052.firebasestorage.app',
    iosBundleId: 'com.alu.kigali.kigaliDirectory',
  );

}